const caseCopy = {
 en:{back:'← All work',skip:'Skip to case study',talk:'Let’s talk ↗',type:'Project type',role:'My role',year:'Year',concept:'Independent concept',self:'Self-initiated product',overview:'Overview',challenge:'The challenge',idea:'The direction',system:'The visual system',flow:'Product flow',process:'Design principles',result:'The result',gallery:'Selected screens',artwork:'The finished work',next:'NEXT PROJECT',live:'View live site ↗',contact:'Have something in mind? Let’s talk ↗',footer:'Designed by me — with colour & curiosity ✳',cv:'Download CV ↓',toolLabel:'Built with',gutenberg:'Catalogue: public-domain books from Project Gutenberg.',notes:'Visual direction and project notes by Akbope. No client outcomes or performance metrics are claimed.'},
 kk:{back:'← Барлық жұмыс',skip:'Кейс мазмұнына өту',talk:'Байланысу ↗',type:'Жоба түрі',role:'Менің рөлім',year:'Жыл',concept:'Тәуелсіз концепт',self:'Өз бастамаммен жасалған өнім',overview:'Жоба туралы',challenge:'Міндет',idea:'Бағыт',system:'Визуал жүйе',flow:'Өнімді пайдалану жолы',process:'Дизайн қағидалары',result:'Нәтиже',gallery:'Таңдалған экрандар',artwork:'Дайын жұмыстар',next:'КЕЛЕСІ ЖОБА',live:'Сайтты ашу ↗',contact:'Идеяңыз бар ма? Сөйлесейік ↗',footer:'Дизайнын өзім жасадым — түс пен қызығушылықпен ✳',cv:'Түйіндемені жүктеу ↓',toolLabel:'Қолданылған технологиялар',gutenberg:'Каталог: Project Gutenberg қорындағы қоғамдық игілікке өткен кітаптар.',notes:'Ақбөпенің визуал бағыты мен жоба жазбалары. Клиент нәтижелері немесе өнімділік көрсеткіштері туралы мәлімдеме жасалмайды.'}
};
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderCase(p,lang='en'){
 const t=caseCopy[lang],e=escapeHTML,digital=p.category==='digital';
 const next=projects[(projects.findIndex(item=>item.key===p.key)+1)%projects.length];
 const section=(n,title,body)=>`<section class="case-section"><div><p class="eyebrow">${n}</p><h2>${title}</h2></div><div>${body}</div></section>`;
 return `<a class="case-breadcrumb" href="index.html#work">${t.back}</a><section class="case-hero"><p class="eyebrow">${digital?t.self:t.concept}${p.year?' · '+p.year:''}</p><h1>${e(p.title)}</h1><p class="lead">${e(p.summary[lang])}</p></section><dl class="case-fact-grid"><div><dt>${t.type}</dt><dd>${p.kind==='self'?t.self:t.concept}</dd></div><div><dt>${t.role}</dt><dd>${e(p.role[lang])}</dd></div>${p.year?`<div><dt>${t.year}</dt><dd>${p.year}</dd></div>`:''}</dl><figure class="case-visual ${digital?'is-digital':''}"><img src="${src(p.files[0])}" alt="${e(p.title)} — ${digital?t.gallery:t.artwork}" fetchpriority="high"></figure>${section('01',t.challenge,`<p>${e(p.challenge[lang])}</p>`)}${section('02',t.idea,`<p>${e(p.idea[lang])}</p>`)}${section('03',t.system,`<p>${e(p.system[lang])}</p>${p.palette?`<div class="palette">${p.palette.map(hex=>`<span class="swatch"><i style="--swatch:${hex}" aria-hidden="true"></i>${hex.toUpperCase()}</span>`).join('')}</div>`:''}${p.tech?`<p class="case-tech">${t.toolLabel}: ${e(p.tech)}${p.key==='mountain'?'<br>'+t.gutenberg:''}</p>`:''}`)}${section('04',digital?t.flow:t.process,`<ol class="case-steps">${p.steps[lang].map(step=>`<li>${e(step)}</li>`).join('')}</ol>`)}<section aria-labelledby="gallery-title"><div class="case-section"><div><p class="eyebrow">05</p><h2 id="gallery-title">${digital?t.gallery:t.artwork}</h2></div><p>${e(p.result[lang])}</p></div><div class="case-gallery ${digital?'digital-gallery':''}">${p.files.map((file,i)=>`<figure><a href="${src(file)}" target="_blank" rel="noopener" aria-label="${e(p.title)} — ${i+1}"><img loading="lazy" decoding="async" src="${src(file)}" alt="${e(p.title)} — ${e(p.captions?.[lang]?.[i]||String(i+1).padStart(2,'0'))}"></a><figcaption>${e(p.captions?.[lang]?.[i]||String(i+1).padStart(2,'0'))}</figcaption></figure>`).join('')}</div></section>${p.live?section('06',t.result,`<p>${e(p.result[lang])}</p><a class="case-live" href="${p.live}" target="_blank" rel="noopener">${t.live}</a>`):''}<a class="next-project" href="${projectHref(next.key)}"><span><small>${t.next}</small>${e(next.title)}</span><span aria-hidden="true">↗</span></a><a class="case-contact" href="index.html#contact">${t.contact}</a>`;
}
